[EXECUTION]
    plot = True
    # of iterations
    N iterations = 10
    #setpoint
    x setpoint = 136
    y setpoint = 201
    inner radius = 10
    outer radius = 30

[CAMERA CALIBRATION]
    background file = ""
    masterflat file = ""
    badpix file = ""

[HITCHHIKER MODE]
    #hitchhiker mode looks for files in a directory you provide
    #it will not directly control the camera if enabled.
    hitchhike = False
    #how often to check the output directory for a new file in seconds
    poll interval = 0.5
    #hitchhiker will raise an error and stop trying to centroid if no file is received by this amount of time
    timeout = 20.0
    #image directory to look for images
    imagedir = /Users/mbottom/Desktop/projects/HSF_exoplanet_imaging/fast_and_furious_wfs/code/dummy_camera_directory

[PID]
    #proportional gain, eg, if 5 pix error-->correct 2.5 if gain = 0.5
    Kp = 0.5
    #integral gain
    Ki = 0.0
    #derivative gain
    Kd = 0.0
    #max PID output in centroid units (quad cell range is roughly -1 to +1)
    output_limits = 0.5

[AO]
    #gain to convert from pixels to TT_OFFSET commands
    tip tilt gain = 0.05
    tip tilt angle (deg) = 90.0
    tip tilt flip x = True
    tip tilt flip y = False
